version: "3.8"

services:
  ocpp-server:
    build: .
    container_name: ocpp-mqtt-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - MQTT_HOST=192.168.X.X
      - MQTT_PORT=1883
      - MQTT_USER=dein_mqtt_benutzername
      - MQTT_PASSWORD=dein_mqtt_passwort
