#!/usr/bin/with-contenv bash

set -e

CONFIG="/data/ocpp.ini"

MQTT_HOST=$(bashio::config 'mqtt_host')
MQTT_PORT=$(bashio::config 'mqtt_port')
MQTT_USER=$(bashio::config 'mqtt_user')
MQTT_PASS=$(bashio::config 'mqtt_password')
OCPP_PORT=$(bashio::config 'ocpp_port')

mkdir -p /data

cp /opt/ocpp/ocpp-default.ini "${CONFIG}"

sed -i "s/^MQTT_HOST=.*/MQTT_HOST=${MQTT_HOST}/" "${CONFIG}"
sed -i "s/^MQTT_PORT=.*/MQTT_PORT=${MQTT_PORT}/" "${CONFIG}"
sed -i "s/^MQTT_USER=.*/MQTT_USER=${MQTT_USER}/" "${CONFIG}"
sed -i "s/^MQTT_PASSWORD=.*/MQTT_PASSWORD=${MQTT_PASS}/" "${CONFIG}"
sed -i "s/^LISTEN0=.*/LISTEN0=${OCPP_PORT}/" "${CONFIG}"

cd /opt/ocpp

exec perl ocpp.pl "${CONFIG}"
